version: "3"

networks:
  test:
    external:
      name: test

services:

  cliOrg2:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == add-org2
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /root/Sample_IOT_BC/chaincode/:/opt/gopath/src/github.com/chaincode
      - /root/Sample_IOT_BC/create_cert/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - /root/Sample_IOT_BC/create_cert/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - /root/Sample_IOT_BC/create_cert/tchannel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      test:
        aliases:
          - cliOrg2.example.com
