Organizations:
    - &Org2
      # DefaultOrg defines the organization which is used in the sampleconfig
      # of the fabric.git development environment
      Name: Org2MSP

      # ID to load the MSP definition as
      ID: Org2MSP

      MSPDir: /root/Sample_IOT_BC/create_cert/organizations/peerOrganizations/org2.example.com/msp

      # Policies defines the set of policies at this level of the config tree
      # For organization policies, their canonical path is usually
      #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Org2MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Org2MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Org2MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Org2MSP.peer')"

      AnchorPeers:
          # AnchorPeers defines the location of peers which can be used
          # for cross org gossip communication.  Note, this value is only
          # encoded in the genesis block in the Application section context
          - Host: peer0.org2.example.com
            Port: 9051
